name: flutter_travel_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_state_city_picker: ^1.2.8
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  dio: ^5.2.1+1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.0.1+1

#Run commands to generate splash screen
#1 flutter clean
#2 flutter pub get
#3 flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: assets/cloudsbackgound.png
  image: assets/airplane.png

flutter:
  uses-material-design: true
  assets: 
    - assets/
