name: flutter_travel_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: ^1.0.2
  #country_state_city_picker: ^1.2.8
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  dio: ^5.2.1+1
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.1
  image_picker: ^1.0.0
  flutter_lints: ^2.0.2

flutter_native_splash:
  color: "006494"
  image: assets/airplane.png
  android: true

  #flutter_native_splash: ^2.0.1+1

#Run commands to generate splash screen
#1 flutter clean
#2 flutter pub get
#3 flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true
  assets: 
    - assets/

